### ISSUE TITLE
user provided sequence chunk?

### ISSUE THREAD

**Issue by jianshu93** [sjaenick/pprodigal#1]
Hi, Sebastian

Any possibility that you make the sequences run for each prodigal process changeable? Offer an input option for a specific number of sequences to run? By the way I think it should be multiprocess version but not a multithread version. Thank you very much for this script!

Jianshu

**Comment by sjaenick** [comment]
Hi Jianshu,

good to hear this is useful. I just implemented your suggestions:

```
  -T TASKS, --tasks TASKS
                        number of prodigal processes to start in parallel
                        (default: 20)
  -C CHUNKSIZE, --chunksize CHUNKSIZE
                        number of input sequences to process within a chunk
                        (default: 2000)
```

Sebastian
