### ISSUE TITLE
duplicated genes after run pprodigal

### ISSUE THREAD

**Issue by jianshu93** [sjaenick/pprodigal#2]
For a contig file, I have an unique contig id let's say >k127_95386, after running you pprodigal, there are 3 copies of >k127_95386_1 gene in the fna output, which I think is strange. When you cut the input fasta contig file into chunks, do they have overlaps? This could be a potential bug and we may have duplicated genes if there are overlap of the chunks.

**Comment by sjaenick** [comment]
Strange, this should not happen. Can you provide steps to reproduce as well as relevant input files?
