### ISSUE TITLE
Missing line break in FASTA output

### ISSUE THREAD

**Issue by snayfach** [sjaenick/pprodigal#4]
The program is not properly writing the final output using the command: 
`pprodigal.py -C 100 -T 64 -m -p meta -i genomes.fa -a proteins.faa &> /dev/null`

Look at this record and notice that the protein sequence has overwritten part of the sequence header line:
> \>OK040792_1 # 1 # 882 # 1 # ID=3136_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.715MTAADPLDMSDLPRHTVRRVMTAEEATELVGTTVPRLDPTDALNRGGLWLDEETGEPVLG

**Comment by sjaenick** [comment]
Thanks for catching this @snayfach!

Issue should be resolved now.
